server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:4201"
              - "http://localhost:8090"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: media-service
          uri: ${MEDIA_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/media/**
        - id: diagnosis-service
          uri: ${DIAGNOSIS_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/diagnoses/**
        - id: repairer-service
          uri: ${REPAIRER_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/repairers/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
